### PR TITLE
"Add location" button and image for comments; Chat Messages considering FuzzFlash radius

### PR DESCRIPTION
**Pull request by zudochkin**
- "Add location" Button
- Upload image on comments
- Pointer cursor for collapsed chat line
- Show only chat messages closer than fuzzflash radius
- Fixed timestamps on modal window
- Fixed bug with "Invalid date" for last_seen field
- Added address field for report form and reports details
- Display all comments with a coords on the reports map

### CODE REVIEW

**Comment by jergagon1** [comment]
Confirm individual report maps are functioning on mobile devices. Tried on safari and chrome on iphone and map did not show up. Maps work in individual report link pages, but not in the main list.

**Comment by jergagon1** [comment]
In main report list in staging app, the type of pet and pet name (if occurs) are missing from the report summary in the list of reports. In the report details, the pet type and name are shown. For example list shows 'Lost' when it should say 'Lost Dog "Sophie"'.

**Comment by jergagon1** [comment]
Confirm text changes from master branch get merged in. For example "Filter" button was changed to say "Search"

**Comment by zudochkin** [comment]
@jergagon1  I'll check 'em all tonight.

**Pull request merged**
